# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ssu_blog/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    mode: '755'
    owner: ubuntu
    group: ubuntu

hook:
  ApplicationStart:
    - location: /home/ubuntu/ssu_blog/scripts/run_new_was.sh
      timeout: 200
      runas: ubuntu
    - location: /home/ubuntu/ssu_blog/scripts/switch.sh
      timeout: 180
      runas: ubuntu
  #ValidateService:
    #- location: /home/ubuntu/ssu_blog/scripts/health_check.sh
      #timeout: 180
      #runas: ubuntu