# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ssu_blog/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 0755

hook:
  BeforeInstall:
    - location: /bin/bash
      timeout: 180
      runas: ubuntu
      args:
        - -c
        - |
          chmod +x /home/ubuntu/ssu_blog/scripts/run_new_was.sh
          chmod +x /home/ubuntu/ssu_blog/scripts/health_check.sh
          chmod +x /home/ubuntu/ssu_blog/scripts/switch.sh

  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/health_check.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 180
      runas: ubuntu