# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ssu_blog/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    mode: '755'
    owner: ubuntu
    group: ubuntu

hook:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 200
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 180
      runas: ubuntu